#define BGM_MIN 1
#define BGM_MUS_CLI2 1
#define BGM_MUS_S2BLVS 2
#define BGM_MUS_S3CLEAR 3
#define BGM_SFX_S1JUMP 4
#define BGM_SFX_S1SELECT 5
#define BGM_SFX_SEGA 6
#define BGM_SFX_SPRING 7
#define BGM_MAX 7
